### ISSUE TITLE
Webhook watching FlowSchema/PriorityLevelConfiguration error

### ISSUE THREAD

**Issue by DanielHouston** [kelvie/cert-manager-webhook-namecheap#3]
Hey there,
The webhook container is unable to watch FlowSchema's and PriorityLevelConfigurations in my cluster @ v1.26.3

0329 13:03:43.790478       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.1/tools/cache/reflector.go:167: Failed to watch *v1beta1.FlowSchema: failed to list *v1beta1.FlowSchema: the server could not find the requested resource
E0329 13:04:18.249198       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.1/tools/cache/reflector.go:167: Failed to watch *v1beta1.PriorityLevelConfiguration: failed to list *v1beta1.PriorityLevelConfiguration: the server could not find the requested resource

Looks like both objects have moved to the v1beta3 group 
`kubectl api-resources -o wide | grep flow
flowschemas                                    flowcontrol.apiserver.k8s.io/v1beta3   false        FlowSchema                       create,delete,deletecollection,get,list,patch,update,watch
prioritylevelconfigurations                    flowcontrol.apiserver.k8s.io/v1beta3   false        PriorityLevelConfiguration       create,delete,deletecollection,get,list,patch,update,watch`

**Comment by kelvie** [comment]
Has anyone tried upgrading client-go to the latest to see if this fixes it? I haven't had time to look into this myself.

```
go get -u k8s.io/client-go
```

**Comment by kelvie** [comment]
Sorry for the late response to this, but `kelvie/cert-manager-webhook-namecheap:v1.0.0` should fix this.

It's also tagged as `latest` so the helm chart will will auto-update if you force it to re-pull (and as I type this out I wonder if that's a good idea).
